services:
  - type: web
    name: sbscr-router
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn serve:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
